# Generated by Django 5.2.4 on 2025-07-22 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESGames', '0003_userprofile_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='ESGames.userprofile')),
                ('videogame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESGames.videogame')),
            ],
            options={
                'unique_together': {('user_profile', 'videogame')},
            },
        ),
    ]
